apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: notes-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: notes-api-app
          image: 916205284554.dkr.ecr.us-east-1.amazonaws.com/notes-api-app:placeholder
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: notes-api-config
            - secretRef:
                name: notes-api-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: ClusterIP
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000