apiVersion: v1
kind: Secret
metadata:
  name: notes-api-secret
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: notesdb  
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: notesdb
